### ISSUE TITLE
CUDA out of memory for sample_diffuser

### ISSUE THREAD

**Issue by m3lionas** [adobe-research/custom-diffusion#20]
Hi,

faced an out of memory error after trying to test out my trained model with sample_diffuser.py. 40 GBs was too little for it. Is there any way to fix this?

Command that I ran:
```
! python src/sample_diffuser.py --delta_ckpt /content/drive/MyDrive/logs/cat/delta.bin --ckpt "stabilityai/stable-diffusion-2-1" --prompt "female face in the style of <new1>"
```
```
dict_keys(['unet', 'modifier_token'])
  0% 0/200 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "src/sample_diffuser.py", line 70, in <module>
    sample(args.ckpt, args.delta_ckpt, args.from_file, args.prompt, args.compress, args.freeze_model)
  File "src/sample_diffuser.py", line 27, in sample
    images = pipe([prompt]*5, num_inference_steps=200, guidance_scale=6., eta=1.).images
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 606, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=prompt_embeds).sample
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py", line 481, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_blocks.py", line 789, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/attention.py", line 291, in forward
    attn_output = self.attn1(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/cross_attention.py", line 160, in forward
    return self.processor(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/cross_attention.py", line 239, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/cross_attention.py", line 203, in get_attention_scores
    attention_probs = attention_probs.to(dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.91 GiB (GPU 0; 39.59 GiB total capacity; 34.67 GiB already allocated; 2.86 GiB free; 34.77 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by nupurkmr9** [comment]
Hi, 

Can you try this with the updated code? 

`python src/sample_diffuser.py --delta_ckpt /content/drive/MyDrive/logs/cat/delta.bin --ckpt "stabilityai/stable-diffusion-2-1" --prompt "female face in the style of <new1>" --batch_size 1`

Previously, there was a fixed batch size during inference. I have changed it to be passed as an argument. Thanks for bringing it up. Hopefully, this should resolve the issue.

**Comment by m3lionas** [comment]
This worked, thanks!
