### ISSUE TITLE
Entry Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/tokenizer/config.json.

### ISSUE THREAD

**Issue by cian0** [adobe-research/custom-diffusion#7]
I am getting this error both through the main repo and the gradio one, trying out 1.4,1.5,2.1 SD versions as well

```15276 163
Connection refused by the server..
19109 164
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 239, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/tokenizer/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1067, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1376, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 257, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-63ab18d6-5143fbe5424472572e730170)

Entry Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/tokenizer/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/sdw/examples/dreambooth/custom-diffusion/custom-diffusion/src/diffuser_training.py", line 1246, in <module>
    main(args)
  File "/workspace/sdw/examples/dreambooth/custom-diffusion/custom-diffusion/src/diffuser_training.py", line 892, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 575, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 776, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.9/site-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1-base does not appear to have a file named tokenizer/config.json. Checkout 'https://huggingface.co/stabilityai/stable-diffusion-2-1-base/main' for available files.
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'custom-diffusion/src/diffuser_training.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-1-base', '--output_dir=results', '--concepts_list=results/temp.json', '--with_prior_preservation', '--prior_loss_weight=1.0', '--resolution=768', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-06', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=2000', '--num_class_images=200', '--initializer_token=ktn+pll+ucd', '--scale_lr', '--hflip', '--modifier_token', '<new1>', '--real_prior', '--use_8bit_adam', '--train_text_encoder', '--gradient_checkpointing']' returned non-zero exit status 1.

**Comment by nupurkmr9** [comment]
Hi,
This seems like a version issue. Can you comment which version of transformers you are using? 
I have tested the code with `transformers==4.25.1` and `diffusers==0.10.0.dev0`.  I think any version greater than this should also work. 

Thanks.

**Comment by batrlatom** [comment]
try to upgrade transformers and diffusers libraries.
