### ISSUE TITLE
Errors in using diffuser version

### ISSUE THREAD

**Issue by OchiaiNao** [adobe-research/custom-diffusion#78]
I have used the training codes from [this](https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion) page, and it returns error like this: 
```Python
Traceback (most recent call last):
  File "/content/diffusers/examples/custom_diffusion/train_custom_diffusion.py", line 37, in <module>
    from huggingface_hub.utils import insecure_hashlib
ImportError: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```
I think it comes from the update of hugging_face, it appeared recently.

**Comment by 2629630207** [comment]
I met the same problem, have you solved it?

**Comment by nupurkmr9** [comment]
Hi, I have huggingface_hub==0.19.4, and I don't face this issue. Can you print the version of huggingface_hub?

**Comment by OchiaiNao** [comment]
> Hi, I have huggingface_hub==0.19.4, and I don't face this issue. Can you print the version of huggingface_hub?

I am using huggingface-hub==0.17.3, coming from the diffusers' setup.py. They had updated the diffusers' setup.py files [here](https://github.com/huggingface/diffusers/blob/c896b841e48b65e561800f829c546f4cf047e634/setup.py) from 
```Python 
huggingface-hub>=0.13.2
```
to 
```Python 
huggingface-hub>=0.19.4
```
Now it works with the newest version.
