### ISSUE TITLE
ImportError: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' 怎么解决？

### ISSUE THREAD

**Issue by zhangyun-w** [adobe-research/custom-diffusion#83]
(baichuan) [root@test LLaMA-Efficient-Tuning]# CUDA_VISIBLE_DEVICES=0 python src/train_bash.py --do_train --model_name_or_path /home/Baichuan-13B/Baichuan-13B-chat --template baichuan --dataset alpaca_gpt4_zh --output_dir baichuan_lora_checkpoint --cutoff_len 512 --per_device_train_batch_size 2 --gradient_accumulation_steps 1 --lr_scheduler_type cosine --logging_steps 10 --save_steps 5000 --learning_rate 5e-5 --num_train_epochs 1.0 --plot_loss --fp16 --lora_target W_pack --lora_rank 8
Traceback (most recent call last):
File "/home/LLaMA-Efficient-Tuning/src/train_bash.py", line 1, in
from llmtuner import run_exp
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/init.py", line 3, in
from llmtuner.api import create_app
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/api/init.py", line 1, in
from llmtuner.api.app import create_app
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/api/app.py", line 22, in
from llmtuner.chat import ChatModel
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/chat/init.py", line 1, in
from llmtuner.chat.chat_model import ChatModel
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/chat/chat_model.py", line 8, in
from llmtuner.data.template import get_template_and_fix_tokenizer
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/data/init.py", line 1, in
from llmtuner.data.loader import get_dataset
File "/home/LLaMA-Efficient-Tuning/src/llmtuner/data/loader.py", line 4, in
from datasets import concatenate_datasets, interleave_datasets, load_dataset, load_from_disk
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/init.py", line 22, in
from .arrow_dataset import Dataset
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 66, in
from .arrow_reader import ArrowReader
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/arrow_reader.py", line 30, in
from .download.download_config import DownloadConfig
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/download/init.py", line 9, in
from .download_manager import DownloadManager, DownloadMode
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/download/download_manager.py", line 31, in
from ..utils import tqdm as hf_tqdm
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/utils/init.py", line 19, in
from .info_utils import VerificationMode
File "/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/datasets/utils/info_utils.py", line 5, in
from huggingface_hub.utils import insecure_hashlib
ImportError: cannot import name 'insecure_hashlib' from 'huggingface_hub.utils' (/usr/local/bin/miniconda3/envs/baichuan/lib/python3.10/site-packages/huggingface_hub/utils/init.py)

**Comment by 1220926326** [comment]
你好，解决了吗？
