### ISSUE TITLE
TypeError: new_forward() got an unexpected keyword argument 'attention_mask'

### ISSUE THREAD

**Issue by fuchao01** [adobe-research/custom-diffusion#9]
**ENV:**
  torch                          1.11.0+cu113
  torchvision                    0.12.0+cu113
  diffusers                      0.11.1
  transformers                   4.25.0

Traceback (most recent call last):
  File "src/diffuser_training.py", line 1252, in <module>
    main(args)
  File "src/diffuser_training.py", line 1152, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 424, in forward
    sample, res_samples = downsample_block(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 777, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, timestep=timestep)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/attention.py", line 498, in forward
    self.attn2(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: new_forward() got an unexpected keyword argument 'attention_mask'

**Comment by nupurkmr9** [comment]
Hi,
This was due to new updates in diffusers 0.11.1.  I have made the appropriate changes in our code that it should work now. Thanks for brining this up.
